# Config file for [Air](https://github.com/cosmtrek/air) in TOML format
root = "."
tmp_dir = "tmp"

[build]
bin = "bin/app"
cmd = "make build && make refresh"
exclude_dir = [".git", "bin", "logs", "tmp", "vendor", "src/dev"]
exclude_regex = [".*_templ.go"]
follow_symlink = false
ignore = ["*_test.go"]
include_ext = ["go", "tpl", "tmpl", "templ", "html"]
