# Config file for [Air](https://github.com/cosmtrek/air) in TOML format
root = "."
tmp_dir = "tmp"

[build]
bin = "bin/app"
cmd = "templ generate && CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o ./bin/app ./main.go"
delay = 1000
exclude_dir = [".git", "bin", "logs", "tmp", "vendor", "src/devUtils"]
exclude_regex = [".*_templ.go"]
follow_symlink = false
ignore = ["*_test.go", "testHelpers.go"]
include_ext = ["go", "tpl", "tmpl", "templ", "html"]

[[watcher]]
build = true
watch = "src/**/*.go"
