basePath: /v1
definitions:
  entity.Contact:
    properties:
      id:
        type: integer
      name:
        type: string
      nickname:
        type: string
      phone:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: northontorga+github@gmail.com
    name: Northon Torga
    url: https://ntorga.com/
  description: 'Clean Architecture & DDD with Go, Tailwind, Alpine.js, HTMX, and SQLite:
    A Proof of Concept'
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Clean DDD TAGHS PoC Contacts
  version: 0.0.1
paths:
  /v1/contact/:
    get:
      consumes:
      - application/json
      description: List contacts.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.Contact'
            type: array
      summary: GetContacts
      tags:
      - contact
swagger: "2.0"
